name: Build global user badges

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'  # Ejecuta todos los días a las 04:00 UTC
  workflow_dispatch:

jobs:
  build-user-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Instalar GH CLI y badgen-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          npm install -g badgen-cli

      - name: Autenticar GH CLI con PAT
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Obtener métricas globales del usuario
        env:
          GH_USER: Jfernandez27
        run: |
          REPO_COUNT=$(gh api graphql -f query='
            query($login:String!) {
              user(login:$login) {
                repositories(ownerAffiliations:[OWNER], isFork:false) { totalCount }
              }
            }' -f login="$GH_USER" --jq '.data.user.repositories.totalCount')

          COMMIT_COUNT=$(gh api graphql -f query='
            query($login:String!) {
              user(login:$login) {
                contributionsCollection {
                  totalCommitContributions
                }
              }
            }' -f login="$GH_USER" --jq '.data.user.contributionsCollection.totalCommitContributions')

          PR_CONTRIB=$(gh api graphql -f query='
            query($login:String!) {
              user(login:$login) {
                contributionsCollection {
                  totalPullRequestContributions
                }
              }
            }' -f login="$GH_USER" --jq '.data.user.contributionsCollection.totalPullRequestContributions')

          ISSUE_CONTRIB=$(gh api graphql -f query='
            query($login:String!) {
              user(login:$login) {
                contributionsCollection {
                  totalIssueContributions
                }
              }
            }' -f login="$GH_USER" --jq '.data.user.contributionsCollection.totalIssueContributions')

          FOLLOWERS=$(gh api graphql -f query='
            query($login:String!) {
              user(login:$login) {
                followers { totalCount }
              }
            }' -f login="$GH_USER" --jq '.data.user.followers.totalCount')

          STARRED=$(gh api graphql -f query='
            query($login:String!) {
              user(login:$login) {
                starredRepositories { totalCount }
              }
            }' -f login="$GH_USER" --jq '.data.user.starredRepositories.totalCount')

          echo "REPO_COUNT=$REPO_COUNT" >> $GITHUB_ENV
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "PR_CONTRIB=$PR_CONTRIB" >> $GITHUB_ENV
          echo "ISSUE_CONTRIB=$ISSUE_CONTRIB" >> $GITHUB_ENV
          echo "FOLLOWERS=$FOLLOWERS" >> $GITHUB_ENV
          echo "STARRED=$STARRED" >> $GITHUB_ENV

      - name: Generar badges SVG
        run: |
          mkdir -p badges
          badgen --label="Repositorios" --status="$REPO_COUNT" --color="0EA5E9" > badges/public-repos.svg
          badgen --label="Commits Totales" --status="$COMMIT_COUNT" --color="10B981" > badges/total-commits.svg
          badgen --label="PR Contributions" --status="$PR_CONTRIB" --color="22C55E" > badges/pr-contrib.svg
          badgen --label="Issue Contributions" --status="$ISSUE_CONTRIB" --color="DC2626" > badges/issue-contrib.svg
          badgen --label="Followers" --status="$FOLLOWERS" --color="FACC15" > badges/followers.svg
          badgen --label="Starred Repos" --status="$STARRED" --color="F97316" > badges/starred.svg
          badgen --label="Languages" --status="PHP | Python | JS" --color="D946EF" > badges/languages.svg

      - name: Commit y push de badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update global user badges'
          file_pattern: 'badges/*.svg'
          token: ${{ secrets.GITHUB_TOKEN }}
